### ISSUE TITLE
Install error - Python

### ISSUE THREAD

**Issue by vanarebane** [adambrgmn/rawly#1]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\vanar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\vanar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\vanar\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vanar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\vanar\Dropbox\Code\Electron\test\node_modules\sharp
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.16.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vanar\AppData\Roaming\npm-cache\_logs\2017-07-28T12_26_26_420Z-debug.log

This is the error I get when trying to install. Python is installed in the machine so...

**Comment by adambrgmn** [comment]
Sorry for late response (I blame vacation 😉). At a first glance it looks like something is not working with the `sharp`-module. I will take a look at this first thing on Monday. But if you like to try it yourself, fork my repo and try upgrading the dependencies. Because it's been awhile since I've done that.
